# Generated by Django 3.2.16 on 2023-01-22 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal', models.CharField(max_length=10)),
                ('program_code', models.CharField(max_length=10)),
                ('exhibition_date', models.DateField(verbose_name='exhibition_date')),
                ('program_start_time', models.DateTimeField(verbose_name='program_start_time')),
                ('average_audience', models.DecimalField(decimal_places=10, max_digits=19, verbose_name='average_audience')),
            ],
            options={
                'verbose_name': 'Audiencia',
                'verbose_name_plural': 'Audiencias',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_arquivo', models.CharField(choices=[('A', 'Arquivo de audiencia'), ('T', 'Arquivo de tempo')], max_length=1, verbose_name='Tipo do arquivo')),
                ('file', models.FileField(null=True, upload_to='', verbose_name='Arquivo')),
            ],
        ),
        migrations.CreateModel(
            name='TempoDisponivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal', models.CharField(max_length=10)),
                ('program_code', models.CharField(max_length=10)),
                ('date', models.DateField(verbose_name='date')),
                ('available_time', models.IntegerField(verbose_name='available_time')),
            ],
            options={
                'verbose_name': 'Tempo Disponivel',
                'verbose_name_plural': 'Tempo Disponivel',
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Processando'), ('F', 'Finalizado'), ('E', 'Erro')], max_length=1, verbose_name='Status')),
                ('finalizado', models.BooleanField(default=False, verbose_name='Finalizado?')),
                ('data_inicio', models.DateTimeField(auto_now=True, verbose_name='Data/Hora de inicío')),
                ('data_final', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora da final')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.file', verbose_name='Arquivo uplaod')),
            ],
            options={
                'verbose_name': 'Pipeline',
                'verbose_name_plural': 'Pipelines',
                'ordering': ['id'],
            },
        ),
    ]
